### Generate Code with SHA1
POST http://localhost:5109/api/code/generate/sha1
Content-Type: application/json

{
  "id": "example-id",
  "salt": "example-salt"
}

### Validate Code with SHA1
POST http://localhost:5109/api/code/validate/sha1
Content-Type: application/json

{
  "id": "example-id",
  "salt": "example-salt",
  "code": "example-code"
}

### Generate Code with HMACSHA256
POST http://localhost:5109/api/code/generate/hmacsha256
Content-Type: application/json

{
  "id": "example-id",
  "salt": "example-salt"
}

### Validate Code with HMACSHA256
POST http://localhost:5109/api/code/validate/hmacsha256
Content-Type: application/json

{
  "id": "example-id",
  "salt": "example-salt",
  "code": "example-code"
}
